language: php

php:
  - 5.6

services:
  - mysql

before_script:
    - mysql -e 'create database symfony;'
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - composer self-update
    - composer install --dev --no-interaction --prefer-source
    - app/console cache:warmup --env=test --quiet

script:
  - app/console doctrine:schema:update --force
  - app/console doctrine:fixtures:load --append --purge-with-truncate
  - phpunit -c app/ --coverage-clover=coverage.clover
  