<?php

namespace AppBundle\Repository;


/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function queryLatest()
    {
        return $this->createQueryBuilder('post')
            ->select('post')
            ->where('post.created <= :now')
            ->orderBy('post.created', 'DESC')
            ->setParameter('now', new \DateTime())
            ->getQuery()
            ->getResult();
    }

    public function getPopulate()
    {
        return $this->createQueryBuilder('post')
            ->select('post')
            ->OrderBy('post.rating', 'DESC')
            ->setMaxResults(5)
            ->getQuery()
            ->getResult();
    }

    public function livesearch($slug)
    {
        $posts = $this->createQueryBuilder('post')
            ->select('post')
            ->getQuery()
            ->getResult();

        $list = "";
        foreach ($posts as $post) {
            $postTitle = $post->getTitle();
            $postTitle1 = str_replace(" ", "-",$postTitle);
            $postTitle2 = lcfirst(str_replace(".", "", $postTitle1));
            if (stristr($postTitle, $slug)) {
                if ($list == "") {
                    $list = "<a href=/blog/posts/" . "$postTitle2" . ">
                     " . "$postTitle" . "
                </a>";
                } else {
                    $list = $list . "<br /><a href=/blog/posts/" . "$postTitle2" . ">
                     " . "$postTitle" . "
                </a>";
                }
            }

        }

        return $list;
    }

    public function getPostsWithTags()
    {
        return $this->createQueryBuilder('post')
            ->select('post, tag')
            ->leftJoin('post.tags', 'tag')
            ->getQuery()
            ->getResult();
    }
}
