<?php

namespace AppBundle\Repository;


/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function queryLatest()
    {
        return $this->createQueryBuilder('post')
            ->select('post')
            ->where('post.created <= :now')
            ->orderBy('post.created', 'DESC')
            ->setParameter('now', new \DateTime())
            ->getQuery()
            ->getResult();
    }

    public function getPopulate()
    {
        return $this->createQueryBuilder('post')
            ->select('post')
            ->OrderBy('post.rating', 'DESC')
            ->setMaxResults(5)
            ->getQuery()
            ->getResult();
    }

    public function livesearch($slug)
    {
        $posts = $this->createQueryBuilder('post')
            ->select('post')
            ->getQuery()
            ->getResult();
        $list = "";
        foreach ($posts as $post) {
            $postTitle = $post->getTitle();
            $postSlug = $post->getSlug();
            if (stristr($postTitle, $slug)) {
                    $list = $list ."<a href=/blog/posts/$postSlug>$postTitle</a><br>";
            }
        }
        return $list;
    }

    public function getPostsWithTags()
    {
        return $this->createQueryBuilder('post')
            ->select('post, tag')
            ->leftJoin('post.tags', 'tag')
            ->getQuery()
            ->getResult();
    }
}
