security:
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        blog_database_users:
            entity:
                class: AppBundle:User


    firewalls:
        main:
            pattern: ^/

            anonymous: true

            form_login:
                check_path: security_login_check
                login_path: security_login_form
                csrf_token_generator: security.csrf.token_manager

            logout:
                path: logout
                target: homepage

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

